version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Dedicated test database for running integration tests
  brain-db-test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_db_test
    # No ports exposed to host; only accessible from other containers
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    # Optionally, add a healthcheck here

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/brain_db?schema=public
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      API_KEY: ${API_KEY}
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app

volumes:
  pgdata:
  pgdata_test:
